version: '3.9'

services:
  bp-app:
    container_name: bp-app
    image: sbecerraz10/bpapp:5.0
    build: .
    ports:
      - "80:8080"
    restart: always
    networks:
      - webNet

networks:
  webNet: