version: '3.9'

services:
  bp-app:
    image: sbecerraz10/bpapp:5.0
    build: .
    restart: always
    
  
  nginx:
    image: nginx:latest
    build: nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - bp-app

